<?php
//require_once 'PHPUnit/Framework.php';

/**
 * Test class for Users.
 * Generated by PHPUnit on 2011-01-28 at 10:47:01.
 */
class UsersTest extends CDbTestCase
{
    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User;
        $this->object->setAttributes(array(
            'login' => 'User',
            'role' => 'administrator',
            'email' => 'email',
            'first_name' => 'example',
            'second_name' => 'example',
            'password' => 'example',
            'salt' => 'exmpl'
        ),
            false
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


    /**
     * @todo Implement testTableName().
     */
    public function testTableName()
    {
        $this->assertTrue($this->object->save(false));
        $userName = User::model()->findByPk(1);
        $this->assertEquals('User', $userName->login);
    }


    /**
     * @todo Implement testPrimaryKey().
     */
    public function testPrimaryKey()
    {
        $this->assertTrue($this->object->save(false));
        $userName = Users::model()->findByPk(1);
        $this->assertEquals('User', $userName->login);
    }
}

// дальнейшие методы для тестирования
